"""medicine catalog fields

Revision ID: 51586e691840
Revises: c3f71a0d5b42
Create Date: 2026-08-18 17:33:23.003811

"""
from alembic import op
import sqlalchemy as sa


revision = '51586e691840'
down_revision = 'c3f71a0d5b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('category', sa.String(length=100), server_default='', nullable=False))
    op.add_column('medicines', sa.Column('price', sa.Numeric(precision=10, scale=2, asdecimal=False), server_default='0', nullable=False))
    op.add_column('medicines', sa.Column('in_stock', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('medicines', sa.Column('dosage', sa.String(length=500), server_default='', nullable=False))
    op.add_column('medicines', sa.Column('notes', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'notes')
    op.drop_column('medicines', 'dosage')
    op.drop_column('medicines', 'in_stock')
    op.drop_column('medicines', 'price')
    op.drop_column('medicines', 'category')
    # ### end Alembic commands ###
